version: '3.8'

services:
  flask_web:
    container_name: flask_web_container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    depends_on:
      - postgres
    restart: unless-stopped

  postgres:
    env_file: .env
    container_name: postgres_flask_container
    image: postgres:14
    volumes:
      - flaskdb:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    restart: unless-stopped

volumes:
    flaskdb:
      driver: local